

spring:
       datasource:
                  url: jdbc:mysql://localhost:3306/dev
                  username: admin
                  password: admin
                  driver-class-name: com.mysql.jdbc.Driver
                  type: com.zaxxer.hikari.HikariDataSource
                  hikari:
                       maximum-pool-size: 15
                       connection-timeout: 60000
                       data-source-properties:
                                        cachePrepStmts: true
                                        prepStmtCacheSize: 250
                                        prepStmtCacheSqlLimit: 2048
                                        cacheResultSetMetadata: true
                       pool-name: mypool
                       connection-test-query: select 1 from dual

       jpa:
          properties:
                    hibernate:
                            show-sql: true
                            format-sql: true


logging:
       level:
            org.hibernate.SQL: DEBUG
            com.zaxxer.hikari.HikariConfig: DEBUG
            org.hibernate.type.descriptor.sql.BasicBinder: TRACE
            root: DEBUG

management:
           endpoint:
                   info:
                       enabled: true
                   health:
                     show-details: always


           endpoints:
                    web:
                       exposure:
                               include: "*"